# Generated by Django 4.0.4 on 2022-06-21 15:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mainCarros', '0001_initial'),
        ('mainVagas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GerenciaVaga',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=8)),
                ('carro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainCarros.carro', unique=True)),
                ('vaga', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='mainVagas.vaga', unique=True)),
            ],
        ),
    ]
